from typing import Protocol


class IUoW[T](Protocol):

    async def __aenter__(self) -> T: ...
    async def __aexit__(self, exc_type, exc, tb): ...


class IJWTManager(Protocol):

    def issue_access(self, user_id: int) -> str: ...
    async def verify(self, token: str) -> int: ...
    async def revoke(self, token: str) -> None: ...


class IPasswordHasher(Protocol):

    def hash(self, password: str) -> str: ...

    def verify(self, password: str, password_hash: str) -> bool: ...
