from typing import Protocol
from common.ports import IUoW, IRole, IPermission


class IRoleRepository(Protocol):

    async def get_by_name(self, name: str) -> IRole | None: ...
    async def upsert(self, name: str) -> int: ...


class IPermissionRepository(Protocol):

    async def get_by_code(self, code: str) -> IPermission | None: ...
    async def upsert(self, code: str) -> int: ...


class IUserRolesRepository(Protocol):

    async def ensure_link(self, user_id: int, role_id: int) -> None: ...


class IRolePermissionsRepository(Protocol):

    async def ensure_link(self, role_id: int, permission_id: int) -> None: ...
    async def delete_link(self, role_id: int, permission_id: int) -> None: ...
    async def get_permissions_for_role(self, role_id: int) -> set[int]: ...
